### ISSUE TITLE
Chat prefix doesn't show up

### ISSUE THREAD

**Issue by LyraGhost** [zachoooo/ZavAutoMessager#3] opened 2017-07-07 17:09 UTC
The messages are showing up but theres no prefix.
The prefix is there for the first few messages, but after a bit it disappears.
It seemed to be affected by commands being run? im not really sure what caused it.

**Comment by zachoooo** [comment] 2017-07-07 17:19
Can you send me a copy of your configuration, any error messages that you're getting, and any commands that you're running that affects this? Thanks.

**Comment by zachoooo** [comment] 2017-07-08 20:04
@LyraGhost Please see the above comment

**Comment by zachoooo** [comment] 2017-07-09 20:36
Marked as Invalid. Cannot reproduce and no message from original ticket creator.

**Closed as completed by zachoooo** 2017-07-09 20:36 UTC
Labels: bug, invalid, awaiting response
