### ISSUE TITLE
Prefix not poping up

### ISSUE THREAD

**Issue by DennisFusha** [zachoooo/ZavAutoMessager#4] opened 2017-07-14 13:53 UTC
A few messages don't have the prefix ?!

**Comment by zachoooo** [comment] 2017-07-14 19:29
@DennisFusha can you send me a copy of your configuration? Thanks!

**Comment by DennisFusha** [comment] 2017-07-14 19:43
[config.txt](https://github.com/zachoooo/ZavAutoMessager/files/1149520/config.txt)

**Comment by zachoooo** [comment] 2017-07-14 23:29
@DennisFusha It seems that the prefix only disappears on multiline messages. This is the intended behavior after the update. Do you want to have the prefix on every single line? If so I'd have to add that in as a configuration option.

**Comment by zachoooo** [comment] 2017-07-14 23:29
@DennisFusha http://i.imgur.com/Xi5uwbL.png

**Comment by DennisFusha** [comment] 2017-07-14 23:38
I want it like the picture u send in 😀

**Comment by zachoooo** [comment] 2017-07-15 00:35
@DennisFusha I just copied your exact config. I didn't actually change anything. Are you running some other chat plugins or are you using a different version of the plugin? Can you send me a screenshot of what appears when you use it?

**Comment by DennisFusha** [comment] 2017-07-15 00:36
Yes DeluxeChat

**Comment by DennisFusha** [comment] 2017-07-15 00:37
Its 3 am here i will send screen when i het up 😀

**Comment by DennisFusha** [comment] 2017-07-15 10:49
![2017-07-15_12 47 18](https://user-images.githubusercontent.com/29520150/28238810-13dea6cc-695c-11e7-86b0-2f96744a76a0.png)
![Uploading 2017-07-15_12.48.55.png…]()

**Comment by zachoooo** [comment] 2017-07-15 20:57
@DennisFusha I dug around the code a bit and tested some stuff out, but I can't seem to replicate this issue. Can you try temporarily uninstalling any other chat related plugins and see if this issue persists. Also are you getting any errors in your console?

**Comment by zachoooo** [comment] 2017-07-15 21:01
@DennisFusha Nevermind, bug identified. I will have this fixed shortly

**Comment by zachoooo** [comment] 2017-07-15 21:10
Fixed in 96b9a61

**Closed as completed by zachoooo** 2017-07-15 21:10 UTC
Labels: bug, awaiting response
